# Generated by Django 4.2.6 on 2023-11-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["date", "title"],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата публикации"),
        ),
    ]
