# Generated by Django 4.2.6 on 2023-11-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_tag_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
