# Generated by Django 4.2.6 on 2023-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("A", "Животные"),
                    ("P", "Растения"),
                    ("M", "Микромир"),
                    ("W", "Вода"),
                    ("N", "Природа"),
                ],
                max_length=20,
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, default="default1.jpg", null=True, upload_to="images/"
            ),
        ),
    ]
