# Generated by Django 4.2.6 on 2023-12-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_remove_article_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
