# Generated by Django 4.2.6 on 2023-12-24 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0009_viewcount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["title"],
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
            },
        ),
        migrations.AlterModelOptions(
            name="viewcount",
            options={
                "ordering": ("-view_date",),
                "verbose_name": "Просмотры",
                "verbose_name_plural": "Просмотры",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="news.tag", verbose_name="Теги"
            ),
        ),
    ]
